Fix AttributeError on present() "fail" case
When the context returns a failure message, the exception handling logic tries to "get" a field from the message string instead of the result dict, causing the error not to be displayed correctly:

`AttributeError: 'str' object has no attribute 'get'`